services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybt_php
    ports:
      - 80:80
    #volumes:
      #- ./php:/var/www/html
  db:
    image: mysql:8.0
    container_name: mybt_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mybt_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:8080"
  dns:
    image: ubuntu/bind9
    container_name: mybt_dns
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
