services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybt_php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mybt_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_body_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mybt_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mybt_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"

  dns:
    image: ubuntu/bind9
    container_name: mybt_dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "5354:53/tcp"
      #- "5354:53/udp"
    volumes:
      - ./docker/config/dns:/etc/bind/
      - ./docker/zones:/var/lib/bind/

volumes:
  mybt_mysql_data:
